// SPDX-FileCopyrightText: 2026 True Positive LLC
// SPDX-License-Identifier: GPL-3.0-only
//
// GENERATED by themes/build.py — do not edit by hand.
// Edit themes/*.itermcolors + themes/index.json, then rerun build.py.

const GALLERY_THEMES = [
  { name:"Neon Midnight", pro:false, status:"shipped \u00b7 default \u00b7 warm-vivid",
    recipe:"the <b>warm-vivid</b> one. neo \u2192 <b>neon</b> (neon gas glows orange-red) on a midnight blue-near-black night \u2014 coral accent, saturated warm palette. Chrome derived.",
    ui:{ accent:"#FF6F5E", highlight:"#F7B5AD", success:"#5FB0A2", warning:"#F5A524", broken:"#E5455E", bg:"#080B12", panel:"#0D121D", panelHi:"#161F32", line:"#212F4B", term:"#05070B", text:"#E9ECF3", termfg:"#CFD6E4", muted:"#898C92" },
    ansi:["#0B0E14","#E5455E","#5FB0A2","#F5A524","#5B8CFF","#B98CFF","#4FC7D6","#C9D1E0","#2A3346","#FF6F5E","#7CE0C4","#FFC860","#8AA6FF","#D0B0FF","#86ECF7","#F2F5FA"],
    sem:{"1": "failure", "2": "success", "3": "warning"}, harm:{"9": "accent"} },
  { name:"Bell Bronze", pro:true, status:"shipped \u00b7 Pro \u00b7 warm-muted \u00b7 hand-tuned",
    recipe:"the <b>warm-muted</b> one. earthy bronze on a <b>warm charcoal</b> base \u2014 the one theme whose chrome stays <b>hand-authored</b> (overrides), not derived.",
    ui:{ accent:"#D49A5C", highlight:"#F2C58A", success:"#5FA89C", warning:"#F5A524", broken:"#E06B6B", bg:"#17130D", panel:"#1F1A12", panelHi:"#29231A", line:"#3A3225", term:"#120F09", text:"#ECE4D5", termfg:"#D8CFBE", muted:"#9E9382" },
    ansi:["#1A150E","#E06B6B","#5FA89C","#D49A5C","#5E86C7","#A98BC7","#5FA8B5","#D8CFBE","#3A3324","#F08A8A","#7FC4B7","#F5A524","#8AAAE0","#C8ADE0","#8FCDD9","#F2ECDE"],
    sem:{"1": "failure", "2": "success", "11": "warning"}, harm:{"3": "accent"} },
  { name:"Neon Cobalt", pro:true, status:"NEW \u00b7 electric",
    recipe:"the <b>loud</b> one. <b>max-saturation electric</b> cobalt on a deep near-black navy, high contrast. Its whole 16-color palette runs hot \u2014 so even terminal output reads unmistakably Cobalt. Chrome derived.",
    ui:{ accent:"#5A6EFF", highlight:"#AAB3F7", success:"#4EFDAC", warning:"#FDCF4E", broken:"#FD4E66", bg:"#050713", panel:"#080B1F", panelHi:"#0E1438", line:"#161D54", term:"#03040B", text:"#E6EAF9", termfg:"#C6CEF0", muted:"#878995" },
    ansi:["#0A0C1A","#FD4E66","#4EFDAC","#FDCF4E","#5A6EFF","#E64EFD","#4EECFD","#C6CEF0","#29305A","#F7929F","#92F7C8","#F7DC92","#A3B0FF","#E992F7","#92EDF7","#F0F3FF"],
    sem:{"1": "failure", "2": "success", "3": "warning"}, harm:{"4": "accent"} },
  { name:"Glacier", pro:true, status:"NEW \u00b7 soft \u00b7 name TBD",
    recipe:"the <b>calm</b> one. <b>soft desaturated pastel</b> (Nord/Catppuccin family) on a distinctly <b>lighter slate</b> base \u2014 low contrast, powder-blue accent. Reads completely differently from Cobalt though both are blue. Chrome derived.",
    ui:{ accent:"#8AA6E8", highlight:"#CAD5F0", success:"#9DDDB8", warning:"#DDCC9D", broken:"#DD9DA1", bg:"#181F30", panel:"#1D263B", panelHi:"#27334F", line:"#334267", term:"#151B29", text:"#D0D5DF", termfg:"#B8BFCE", muted:"#818793" },
    ansi:["#202636","#DD9DA1","#9DDDB8","#DDCC9D","#8AA6E8","#CC9DDD","#9DD4DD","#B8BFCE","#414B68","#E7C5C7","#C5E7D4","#E7DEC5","#C0CDEC","#DEC5E7","#C5E3E7","#E4E9F2"],
    sem:{"1": "failure", "2": "success", "3": "warning"}, harm:{"4": "accent"} },
  { name:"Dracula", ref:true, status:"reference \u00b7 imported",
    recipe:"imported .itermcolors \u2192 chrome derived. Vivid pink/purple/cyan/green; still pins green=success \u00b7 red=failure \u00b7 yellow=warning.",
    ui:{ accent:"#BD93F9", highlight:"#FF79C6", success:"#50FA7B", warning:"#F1FA8C", broken:"#FF5555", bg:"#2B2E3D", panel:"#323546", panelHi:"#3E4258", line:"#4D526D", term:"#282A36", text:"#FFFFFF", termfg:"#F8F8F2", muted:"#A5A6AB" },
    ansi:["#21222C","#FF5555","#50FA7B","#F1FA8C","#BD93F9","#FF79C6","#8BE9FD","#F8F8F2","#6272A4","#FF6E6E","#69FF94","#FFFFA5","#D6ACFF","#FF92DF","#A4FFFF","#FFFFFF"],
    sem:{"1": "failure", "2": "success", "3": "warning"}, harm:{"4": "accent"} },
  { name:"Nord", ref:true, status:"reference \u00b7 imported",
    recipe:"imported .itermcolors \u2192 chrome derived. Arctic, desaturated, low-contrast \u2014 the canonical calm palette; Glacier's family.",
    ui:{ accent:"#88C0D0", highlight:"#BFD9E1", success:"#A3BE8C", warning:"#EBCB8B", broken:"#BF616A", bg:"#313847", panel:"#374050", panelHi:"#444E62", line:"#525F77", term:"#2E3440", text:"#F2F4F8", termfg:"#D8DEE9", muted:"#A0A3AB" },
    ansi:["#3B4252","#BF616A","#A3BE8C","#EBCB8B","#81A1C1","#B48EAD","#88C0D0","#E5E9F0","#4C566A","#BF616A","#A3BE8C","#EBCB8B","#81A1C1","#B48EAD","#8FBCBB","#ECEFF4"],
    sem:{"1": "failure", "2": "success", "3": "warning"}, harm:{"6": "accent"} },
  { name:"Gruvbox Dark", ref:true, status:"reference \u00b7 imported",
    recipe:"imported .itermcolors \u2192 chrome derived. Warm retro earthy \u2014 the template Bronze reaches for.",
    ui:{ accent:"#FABD2F", highlight:"#FE8019", success:"#98971A", warning:"#D79921", broken:"#CC241D", bg:"#2E2C2C", panel:"#363434", panelHi:"#454343", line:"#585454", term:"#282828", text:"#F3EAD2", termfg:"#EBDBB2", muted:"#9E998B" },
    ansi:["#282828","#CC241D","#98971A","#D79921","#458588","#B16286","#689D6A","#A89984","#928374","#FB4934","#B8BB26","#FABD2F","#83A598","#D3869B","#8EC07C","#EBDBB2"],
    sem:{"1": "failure", "2": "success", "3": "warning"}, harm:{"11": "accent"} },
  { name:"Catppuccin Mocha", ref:true, status:"reference \u00b7 imported",
    recipe:"imported .itermcolors \u2192 chrome derived. Soft modern pastel; mauve accent isn't a palette slot, so it's an explicit accent override.",
    ui:{ accent:"#CBA6F7", highlight:"#F5C2E7", success:"#A6E3A1", warning:"#F9E2AF", broken:"#F38BA8", bg:"#212135", panel:"#27273E", panelHi:"#333351", line:"#414167", term:"#1E1E2E", text:"#EEF1FB", termfg:"#CDD6F4", muted:"#9798A5" },
    ansi:["#45475A","#F38BA8","#A6E3A1","#F9E2AF","#89B4FA","#F5C2E7","#94E2D5","#BAC2DE","#585B70","#F38BA8","#A6E3A1","#F9E2AF","#89B4FA","#F5C2E7","#94E2D5","#A6ADC8"],
    sem:{"1": "failure", "2": "success", "3": "warning"}, harm:{} },
];

if (typeof window !== "undefined") window.GALLERY_THEMES = GALLERY_THEMES;
